// internal/generator/emit.go
package generator

import (
	"fmt"
	"io"
	"strings"
	"text/template"
)

const fileSkeleton = `// Code generated by internal/generator. DO NOT EDIT.
package generated

import (
	"fmt"
	"os"
{{if .NeedsTime}}	gotime "time"
{{end}}
	"github.com/spf13/cobra"
{{if .NeedsUUID}}	"github.com/google/uuid"
{{end}}{{if .NeedsEmail}}	openapi_types "github.com/oapi-codegen/runtime/types"
{{end}}	"golang.org/x/term"

	"github.com/trustattic/trustattic-cli/internal/cli"
{{if .NeedsClient}}	"github.com/trustattic/trustattic-cli/internal/client"
{{end}})
{{.Body}}`

var fileTmpl = template.Must(template.New("file").Parse(fileSkeleton))

// GroupByTag buckets cmds by their Spec.Tag, preserving each bucket's
// relative order.
func GroupByTag(cmds []GeneratedCommand) map[string][]GeneratedCommand {
	groups := map[string][]GeneratedCommand{}
	for _, c := range cmds {
		groups[c.Spec.Tag] = append(groups[c.Spec.Tag], c)
	}
	return groups
}

// flagValueKinds returns every distinct ValueKind used by c's path-param
// flags (including the positional one, if any) and by c's body flags,
// respectively - used to decide which conversion-only imports a tag file
// needs.
func flagValueKinds(c GeneratedCommand) (pathKinds, bodyKinds []ValueKind) {
	for _, f := range c.Flags {
		pathKinds = append(pathKinds, f.Value)
	}
	if c.PositionalFlag != nil {
		pathKinds = append(pathKinds, c.PositionalFlag.Value)
	}
	for _, f := range c.BodyFlags {
		bodyKinds = append(bodyKinds, f.Value)
	}
	return pathKinds, bodyKinds
}

// EmitTagFile renders the Go source declaring one New<OperationID>Command
// function per entry in cmds to w. Every entry is expected to share the
// same Spec.Tag (call GroupByTag first and emit one file per group).
func EmitTagFile(w io.Writer, cmds []GeneratedCommand) error {
	var body strings.Builder
	var needsUUID, needsEmail, needsTime, needsClient bool
	for _, c := range cmds {
		body.WriteString("\n")
		body.WriteString(renderCommandFunc(c))

		// A command with an unsupported-required-body-prop stub RunE never
		// emits a client.-qualified expression or a conversion call at all
		// (see renderCommandFunc) - its Flags/BodyFlags ValueKinds and
		// HasParams/HasBody are irrelevant to this file's import needs.
		if len(c.UnsupportedRequiredBodyProps) > 0 {
			continue
		}

		// The client package is only referenced when a command builds a
		// client.<OperationID>Params or client.<OperationID>JSONRequestBody
		// value - some real operations (e.g. the "common" healthcheck
		// endpoint) have neither, so unconditionally importing it would
		// leave it unused in a tag file made up entirely of such commands.
		// A body with no flat properties (see below) is passed as a literal
		// nil, not a client.-qualified struct literal, so it doesn't count.
		if c.Spec.Operation.HasParams || (c.Spec.Operation.HasBody && len(c.BodyFlags) > 0) {
			needsClient = true
		}

		pathKinds, bodyKinds := flagValueKinds(c)
		for _, v := range pathKinds {
			if v == ValueUUID {
				needsUUID = true
			}
		}
		for _, v := range bodyKinds {
			switch v {
			case ValueEmail:
				needsEmail = true
			case ValueDateTime:
				needsTime = true
			}
		}
	}
	return fileTmpl.Execute(w, struct {
		Body        string
		NeedsUUID   bool
		NeedsEmail  bool
		NeedsTime   bool
		NeedsClient bool
	}{Body: body.String(), NeedsUUID: needsUUID, NeedsEmail: needsEmail, NeedsTime: needsTime, NeedsClient: needsClient})
}

func renderCommandFunc(c GeneratedCommand) string {
	opID := c.Spec.Operation.OperationID
	var b strings.Builder

	fmt.Fprintf(&b, "func New%sCommand() *cobra.Command {\n", opID)
	for _, f := range c.Flags {
		fmt.Fprintf(&b, "\tvar %s string\n", f.GoIdent)
	}
	for _, f := range c.BodyFlags {
		fmt.Fprintf(&b, "\tvar %s %s\n", f.GoIdent, goType(f.Kind))
	}

	use := c.Spec.Verb
	args := "cobra.NoArgs"
	if c.PositionalFlag != nil {
		use = fmt.Sprintf("%s <%s>", c.Spec.Verb, c.Spec.Positional.Name)
		args = "cobra.ExactArgs(1)"
	}
	fmt.Fprintf(&b, "\tcmd := &cobra.Command{\n\t\tUse:  %q,\n", use)
	if c.Spec.Operation.Summary != "" {
		fmt.Fprintf(&b, "\t\tShort: %q,\n", c.Spec.Operation.Summary)
	}
	if long := longHelp(c); long != "" {
		fmt.Fprintf(&b, "\t\tLong: %q,\n", long)
	}
	fmt.Fprintf(&b, "\t\tArgs: %s,\n\t\tRunE: func(cmd *cobra.Command, args []string) error {\n", args)

	if len(c.UnsupportedRequiredBodyProps) > 0 {
		// This operation requires a body property (an object/array/oneOf
		// shape) that has no flat CLI representation - see isFlatScalar and
		// BuildGeneratedCommands. Sending the request anyway would silently
		// omit a field the server requires, so fail fast instead, before
		// touching config, auth, or the network. Flags for this command's
		// other (flat) properties, if any, are still declared and shown in
		// --help below - only RunE is replaced.
		fmt.Fprintf(&b, "\t\t\treturn fmt.Errorf(%q)\n", unsupportedBodyError(c.UnsupportedRequiredBodyProps))
	} else {
		b.WriteString("\t\t\tcfg, err := cli.LoadConfig()\n\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
		for _, f := range c.Flags {
			if !f.Optional {
				continue
			}
			fmt.Fprintf(&b, "\t\t\tif %s == \"\" {\n\t\t\t\t%s = cfg.CurrentProject\n\t\t\t}\n", f.GoIdent, f.GoIdent)
			// %q, not %s: f.Name is spec-derived, and every other
			// spec-derived value interpolated into generated Go source in
			// this file is quoted the same way so a malformed name can
			// never terminate the string literal it lands in.
			noProjectMsg := fmt.Sprintf("no project set: pass --%s or run `trustattic use <project>`", f.Name)
			fmt.Fprintf(&b, "\t\t\tif %s == \"\" {\n\t\t\t\treturn fmt.Errorf(%q)\n\t\t\t}\n", f.GoIdent, noProjectMsg)
		}
		b.WriteString("\t\t\tapiClient, err := cli.NewAPIClient(cfg)\n\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")

		// The real generated client method takes path parameters as positional
		// Go arguments in URL order. c.Flags is already every path param
		// *except* the positional one, in URL order, and (per naming.go) the
		// positional one - when present - is always the URL's last path param.
		// So "flags first, positional last" here reproduces URL order exactly;
		// do not reorder this.
		// cmd.Context(), not context.Background(): Fang runs the root
		// command via root.ExecuteContext, so a generated command that uses
		// the command's own context inherits whatever cancellation the root
		// context carries, instead of pinning an uncancellable one.
		//
		// NB: fang.Execute only installs a signal.NotifyContext when it's
		// given WithNotifySignal (see fang@v1.0.0 fang.go:167), and
		// cmd/trustattic/main.go passes no options - so today this context
		// is still the plain context.Background() main hands to
		// fang.Execute, and Ctrl-C is handled by Go's default (fatal)
		// signal disposition. This makes the plumbing correct and ready;
		// graceful cancellation needs that one option added in main.go.
		callArgs := []string{"cmd.Context()"}
		for _, f := range c.Flags {
			pre, expr := convertPathParam(f.Value, f.GoIdent, f.GoIdent, "--"+f.Name)
			b.WriteString(pre)
			callArgs = append(callArgs, expr)
		}
		if c.PositionalFlag != nil {
			label := fmt.Sprintf("<%s>", c.Spec.Positional.Name)
			pre, expr := convertPathParam(c.PositionalFlag.Value, c.PositionalFlag.GoIdent, "args[0]", label)
			b.WriteString(pre)
			callArgs = append(callArgs, expr)
		}
		// oapi-codegen only generates a <OperationID>Params argument when the
		// operation declares at least one parameter (path, header, or query) in
		// the spec - a handful of real operations (e.g. the "common" healthcheck
		// endpoint) declare none at all, and WithResponse simply omits the
		// argument for those.
		if c.Spec.Operation.HasParams {
			callArgs = append(callArgs, fmt.Sprintf("&client.%sParams{}", opID))
		}
		if c.Spec.Operation.HasBody {
			if len(c.BodyFlags) == 0 {
				// Every body property this operation declares has no flat CLI
				// representation (or the body's schema is unconstrained, e.g.
				// `schema: {}`, which oapi-codegen types as `interface{}`) - a
				// `client.<OperationID>JSONRequestBody{}` composite literal
				// isn't valid Go for an interface type, and there's nothing to
				// populate either way, so pass nil.
				callArgs = append(callArgs, "nil")
			} else {
				var pre strings.Builder
				var props strings.Builder
				for _, f := range c.BodyFlags {
					p, expr := bodyPropExpr(f)
					pre.WriteString(p)
					fmt.Fprintf(&props, "\t\t\t\t%s: %s,\n", pascalCase(f.GoIdent), expr)
				}
				b.WriteString(pre.String())
				callArgs = append(callArgs, fmt.Sprintf("client.%sJSONRequestBody{\n%s\t\t\t}", opID, props.String()))
			}
		}
		fmt.Fprintf(&b, "\t\t\tresp, err := apiClient.%sWithResponse(\n\t\t\t\t%s,\n\t\t\t)\n", opID, strings.Join(callArgs, ",\n\t\t\t\t"))

		b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
		b.WriteString("\t\t\tif resp.StatusCode() >= 400 {\n\t\t\t\tcli.RenderError(cmd.ErrOrStderr(), &cli.APIError{StatusCode: resp.StatusCode(), Body: resp.Body})\n\t\t\t\treturn fmt.Errorf(\"request failed with status %d\", resp.StatusCode())\n\t\t\t}\n")
		b.WriteString("\t\t\tmode := cli.ModeAuto\n\t\t\tif out, _ := cmd.Flags().GetString(\"output\"); out == \"json\" {\n\t\t\t\tmode = cli.ModeJSON\n\t\t\t}\n")
		b.WriteString("\t\t\tisTTY := term.IsTerminal(int(os.Stdout.Fd()))\n\t\t\treturn cli.Render(cmd.OutOrStdout(), mode, isTTY, resp.Body)\n")
	}
	b.WriteString("\t\t},\n\t}\n")

	for _, f := range c.Flags {
		fmt.Fprintf(&b, "\tcmd.Flags().StringVar(&%s, %q, \"\", %q)\n", f.GoIdent, f.Name, flagUsage(f))
		if f.Required {
			fmt.Fprintf(&b, "\t_ = cmd.MarkFlagRequired(%q)\n", f.Name)
		}
	}
	for _, f := range c.BodyFlags {
		setter, zero := "StringVar", `""`
		switch f.Kind {
		case KindBool:
			setter, zero = "BoolVar", "false"
		case KindInt:
			setter, zero = "IntVar", "0"
		}
		fmt.Fprintf(&b, "\tcmd.Flags().%s(&%s, %q, %s, %q)\n", setter, f.GoIdent, f.Name, zero, flagUsage(f))
		if f.Required {
			fmt.Fprintf(&b, "\t_ = cmd.MarkFlagRequired(%q)\n", f.Name)
		}
	}
	b.WriteString("\treturn cmd\n}\n")
	return b.String()
}

// flagUsage builds a flag's Cobra usage string from its spec-supplied
// description (FlagDef.Help, which already falls back to the flag name when
// the spec has none), annotated with whether the flag must be supplied.
// Cobra doesn't mark required flags in --help output on its own, and the
// project flag's current-project fallback isn't derivable from the spec at
// all, so both are spelled out here.
func flagUsage(f FlagDef) string {
	switch {
	case f.Optional:
		return f.Help + " (falls back to the current project set via `trustattic use`)"
	case f.Required:
		return f.Help + " (required)"
	default:
		return f.Help
	}
}

// longHelp builds a command's Cobra Long description. It's only non-empty
// when there's something to say beyond the operation's summary: today, that
// a body property exists which can never be set from the CLI (see
// GeneratedCommand.DroppedOptionalBodyProps). Cobra shows Long instead of
// Short in --help, so the summary is repeated as its first line.
func longHelp(c GeneratedCommand) string {
	if len(c.DroppedOptionalBodyProps) == 0 {
		return ""
	}
	names := make([]string, len(c.DroppedOptionalBodyProps))
	for i, p := range c.DroppedOptionalBodyProps {
		names[i] = p.Name
	}
	note := fmt.Sprintf(
		"Note: the following fields cannot be set via CLI flags and are always omitted from the request: %s.",
		strings.Join(names, ", "),
	)
	if c.Spec.Operation.Summary == "" {
		return note
	}
	return c.Spec.Operation.Summary + "\n\n" + note
}

// unsupportedBodyError builds the message for a command whose operation
// requires at least one body property isFlatScalar filtered out of
// BodyFlags (see UnsupportedRequiredBodyProps). It names every such
// property so the generic, spec-driven rule ("required && !isFlatScalar")
// stays legible no matter which operation(s) it fires for.
func unsupportedBodyError(props []UnsupportedBodyProp) string {
	parts := make([]string, len(props))
	for i, p := range props {
		typ := p.Type
		if typ == "" {
			typ = "oneOf/unknown"
		}
		parts[i] = fmt.Sprintf("%q (type %q)", p.Name, typ)
	}
	return fmt.Sprintf(
		"this command is not yet supported: request body field(s) %s cannot be set via CLI flags",
		strings.Join(parts, ", "),
	)
}

// convertPathParam returns the Go expression that should be passed as a
// path-parameter call argument to <OperationID>WithResponse, plus any Go
// statements that must run before the call to produce it. rawExpr is how
// the raw string value is available (a flag variable's Go identifier, or
// "args[0]" for the trailing positional); varName is a Go-identifier-safe
// name to derive a local variable from (rawExpr itself isn't always a valid
// identifier, e.g. "args[0]"); label identifies the parameter in the
// generated error message (e.g. "--account-id" or "<account_id>").
//
// Only ValueUUID needs a conversion here: every path parameter is required
// by construction (OpenAPI path parameters are always required), so unlike
// bodyPropExpr there's no optional/pointer case to special-case, and no
// other ValueKind maps to a distinct Go type for a path parameter in the
// current spec.
func convertPathParam(value ValueKind, varName, rawExpr, label string) (pre, expr string) {
	if value != ValueUUID {
		return "", rawExpr
	}
	parsedVar := varName + "Parsed"
	pre = fmt.Sprintf(
		"\t\t\t%s, err := uuid.Parse(%s)\n\t\t\tif err != nil {\n\t\t\t\treturn fmt.Errorf(%q, err)\n\t\t\t}\n",
		parsedVar, rawExpr, "invalid "+label+": %w",
	)
	return pre, parsedVar
}

// bodyPropExpr returns the Go expression assigned to a JSONRequestBody
// struct field for body flag f, plus any Go statements that must run before
// the struct literal to produce it. Whether the real field is a pointer or
// a plain value follows oapi-codegen's own rule: a required property
// becomes a plain value, an optional one a pointer - so f.Required (not
// f.Value) decides pointer-ness, while f.Value decides whether the raw
// flag's string/bool/int value needs converting to a distinct Go type
// first (see ValueKind).
func bodyPropExpr(f FlagDef) (pre, expr string) {
	switch f.Value {
	case ValueEmail:
		conv := fmt.Sprintf("openapi_types.Email(%s)", f.GoIdent)
		if f.Required {
			return "", conv
		}
		// An unset optional email flag must stay nil rather than becoming a
		// pointer to an empty openapi_types.Email - unlike a plain optional
		// string, the real client rejects an empty value against its email
		// format validation at marshal time.
		localVar := f.GoIdent + "Email"
		pre = fmt.Sprintf(
			"\t\t\tvar %s *openapi_types.Email\n\t\t\tif %s != \"\" {\n\t\t\t\temail := %s\n\t\t\t\t%s = &email\n\t\t\t}\n",
			localVar, f.GoIdent, conv, localVar,
		)
		return pre, localVar
	case ValueDateTime:
		// The "time" package is imported as gotime in generated files
		// specifically so a body property literally named "time" (its
		// GoIdent, "time", would otherwise shadow the package within this
		// function - see ScheduleRunPost in the real spec) can't break the
		// call below.
		parsedVar := f.GoIdent + "Parsed"
		errMsg := "invalid --" + f.Name + ": %w"
		if f.Required {
			pre = fmt.Sprintf(
				"\t\t\t%s, err := gotime.Parse(gotime.RFC3339, %s)\n\t\t\tif err != nil {\n\t\t\t\treturn fmt.Errorf(%q, err)\n\t\t\t}\n",
				parsedVar, f.GoIdent, errMsg,
			)
			return pre, parsedVar
		}
		pre = fmt.Sprintf(
			"\t\t\tvar %s *gotime.Time\n\t\t\tif %s != \"\" {\n\t\t\t\tparsed, err := gotime.Parse(gotime.RFC3339, %s)\n\t\t\t\tif err != nil {\n\t\t\t\t\treturn fmt.Errorf(%q, err)\n\t\t\t\t}\n\t\t\t\t%s = &parsed\n\t\t\t}\n",
			parsedVar, f.GoIdent, f.GoIdent, errMsg, parsedVar,
		)
		return pre, parsedVar
	default: // ValuePlain
		if f.Required {
			return "", f.GoIdent
		}
		return "", "&" + f.GoIdent
	}
}

func goType(k BodyFlagKind) string {
	switch k {
	case KindBool:
		return "bool"
	case KindInt:
		return "int"
	default:
		return "string"
	}
}

// pascalCase capitalizes a GoIdent-style camelCase name into the PascalCase
// oapi-codegen uses for exported JSON request-body struct fields (e.g.
// "name" -> "Name"). This covers every plain-word body property in the
// current spec. oapi-codegen applies its own initialism rules for words
// like "url"/"id" (e.g. a property named "logo_url" becomes struct field
// "LogoURL", not "LogoUrl") - if `go build` (Task 15) reports an unknown
// field for a specific property, check its real name with
// `go doc ./internal/client <OperationID>JSONRequestBody` and special-case
// it in this function.
func pascalCase(camel string) string {
	if camel == "" {
		return camel
	}
	return strings.ToUpper(camel[:1]) + camel[1:]
}

// EmitRegisterFile renders register.gen.go, which wires every command in
// cmds onto its tag/group parent. Task 11's BuildCommandSpecs already
// empties Spec.Tag for what was the OpenAPI "common" tag (its commands
// don't belong under a real resource) — an empty Tag here means "attach
// directly to root, ungrouped," per the design spec.
func EmitRegisterFile(w io.Writer, cmds []GeneratedCommand) error {
	var b strings.Builder
	b.WriteString("// Code generated by internal/generator. DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	b.WriteString("import (\n\t\"fmt\"\n\n\t\"github.com/spf13/cobra\"\n)\n\n")
	b.WriteString("func getOrAddCommand(parent *cobra.Command, use string) *cobra.Command {\n")
	b.WriteString("\tfor _, c := range parent.Commands() {\n\t\tif c.Name() == use {\n\t\t\treturn c\n\t\t}\n\t}\n")
	// A group node ("account", "tokens", "restore", ...) isn't an OpenAPI
	// operation, so there's no spec summary to use for its Short. A plain
	// generic label is a presentational default, deliberately not
	// spec-driven, and beats leaving every group blank in --help.
	b.WriteString("\tc := &cobra.Command{Use: use, Short: fmt.Sprintf(\"%s commands\", use)}\n\tparent.AddCommand(c)\n\treturn c\n}\n\n")
	b.WriteString("// Register wires every generated command onto root.\n")
	b.WriteString("func Register(root *cobra.Command) {\n")

	declared := map[string]bool{}
	for _, c := range cmds {
		opID := c.Spec.Operation.OperationID
		if c.Spec.Tag == "" {
			fmt.Fprintf(&b, "\troot.AddCommand(New%sCommand())\n", opID)
			continue
		}

		parentVar := "root"
		pathKey := c.Spec.Tag
		tagVar := c.Spec.Tag + "Cmd"
		if !declared[pathKey] {
			fmt.Fprintf(&b, "\t%s := getOrAddCommand(%s, %q)\n", tagVar, parentVar, c.Spec.Tag)
			declared[pathKey] = true
		}
		parentVar = tagVar

		for _, g := range c.Spec.Group {
			pathKey += "/" + g
			groupVar := c.Spec.Tag + pascalCase(g) + "Cmd"
			if !declared[pathKey] {
				fmt.Fprintf(&b, "\t%s := getOrAddCommand(%s, %q)\n", groupVar, parentVar, g)
				declared[pathKey] = true
			}
			parentVar = groupVar
		}

		fmt.Fprintf(&b, "\t%s.AddCommand(New%sCommand())\n", parentVar, opID)
	}

	b.WriteString("}\n")
	_, err := w.Write([]byte(b.String()))
	return err
}
