// internal/generator/emit.go
package generator

import (
	"fmt"
	"io"
	"strings"
	"text/template"
)

const fileSkeleton = `// Code generated by internal/generator. DO NOT EDIT.
package generated

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"golang.org/x/term"

	"github.com/trustattic/trustattic-cli/internal/cli"
	"github.com/trustattic/trustattic-cli/internal/client"
)
{{.Body}}`

var fileTmpl = template.Must(template.New("file").Parse(fileSkeleton))

// GroupByTag buckets cmds by their Spec.Tag, preserving each bucket's
// relative order.
func GroupByTag(cmds []GeneratedCommand) map[string][]GeneratedCommand {
	groups := map[string][]GeneratedCommand{}
	for _, c := range cmds {
		groups[c.Spec.Tag] = append(groups[c.Spec.Tag], c)
	}
	return groups
}

// EmitTagFile renders the Go source declaring one New<OperationID>Command
// function per entry in cmds to w. Every entry is expected to share the
// same Spec.Tag (call GroupByTag first and emit one file per group).
func EmitTagFile(w io.Writer, cmds []GeneratedCommand) error {
	var body strings.Builder
	for _, c := range cmds {
		body.WriteString("\n")
		body.WriteString(renderCommandFunc(c))
	}
	return fileTmpl.Execute(w, struct{ Body string }{Body: body.String()})
}

func renderCommandFunc(c GeneratedCommand) string {
	opID := c.Spec.Operation.OperationID
	var b strings.Builder

	fmt.Fprintf(&b, "func New%sCommand() *cobra.Command {\n", opID)
	for _, f := range c.Flags {
		fmt.Fprintf(&b, "\tvar %s string\n", f.GoIdent)
	}
	for _, f := range c.BodyFlags {
		fmt.Fprintf(&b, "\tvar %s %s\n", f.GoIdent, goType(f.Kind))
	}

	use := c.Spec.Verb
	args := "cobra.NoArgs"
	if c.PositionalFlag != nil {
		use = fmt.Sprintf("%s <%s>", c.Spec.Verb, c.Spec.Positional.Name)
		args = "cobra.ExactArgs(1)"
	}
	fmt.Fprintf(&b, "\tcmd := &cobra.Command{\n\t\tUse:  %q,\n\t\tArgs: %s,\n\t\tRunE: func(cmd *cobra.Command, args []string) error {\n", use, args)

	b.WriteString("\t\t\tcfg, err := cli.LoadConfig()\n\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
	for _, f := range c.Flags {
		if !f.Optional {
			continue
		}
		fmt.Fprintf(&b, "\t\t\tif %s == \"\" {\n\t\t\t\t%s = cfg.CurrentProject\n\t\t\t}\n", f.GoIdent, f.GoIdent)
		fmt.Fprintf(&b, "\t\t\tif %s == \"\" {\n\t\t\t\treturn fmt.Errorf(\"no project set: pass --%s or run `trustattic use <project>`\")\n\t\t\t}\n", f.GoIdent, f.Name)
	}
	b.WriteString("\t\t\tapiClient, err := cli.NewAPIClient(cfg)\n\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")

	// The real generated client method takes path parameters as positional
	// Go arguments in URL order. c.Flags is already every path param
	// *except* the positional one, in URL order, and (per naming.go) the
	// positional one - when present - is always the URL's last path param.
	// So "flags first, positional last" here reproduces URL order exactly;
	// do not reorder this.
	callArgs := []string{"context.Background()"}
	for _, f := range c.Flags {
		callArgs = append(callArgs, f.GoIdent)
	}
	if c.PositionalFlag != nil {
		callArgs = append(callArgs, "args[0]")
	}
	callArgs = append(callArgs, fmt.Sprintf("&client.%sParams{}", opID))
	if c.Spec.Operation.HasBody {
		var props strings.Builder
		for _, f := range c.BodyFlags {
			fmt.Fprintf(&props, "\t\t\t\t%s: &%s,\n", pascalCase(f.GoIdent), f.GoIdent)
		}
		callArgs = append(callArgs, fmt.Sprintf("client.%sJSONRequestBody{\n%s\t\t\t}", opID, props.String()))
	}
	fmt.Fprintf(&b, "\t\t\tresp, err := apiClient.%sWithResponse(\n\t\t\t\t%s,\n\t\t\t)\n", opID, strings.Join(callArgs, ",\n\t\t\t\t"))

	b.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
	b.WriteString("\t\t\tif resp.StatusCode() >= 400 {\n\t\t\t\tcli.RenderError(cmd.ErrOrStderr(), &cli.APIError{StatusCode: resp.StatusCode(), Body: resp.Body})\n\t\t\t\treturn fmt.Errorf(\"request failed with status %d\", resp.StatusCode())\n\t\t\t}\n")
	b.WriteString("\t\t\tmode := cli.ModeAuto\n\t\t\tif out, _ := cmd.Flags().GetString(\"output\"); out == \"json\" {\n\t\t\t\tmode = cli.ModeJSON\n\t\t\t}\n")
	b.WriteString("\t\t\tisTTY := term.IsTerminal(int(os.Stdout.Fd()))\n\t\t\treturn cli.Render(cmd.OutOrStdout(), mode, isTTY, resp.Body)\n")
	b.WriteString("\t\t},\n\t}\n")

	for _, f := range c.Flags {
		help := f.Name
		if f.Optional {
			help = fmt.Sprintf("%s (falls back to the current project set via `trustattic use`)", f.Name)
		}
		fmt.Fprintf(&b, "\tcmd.Flags().StringVar(&%s, %q, \"\", %q)\n", f.GoIdent, f.Name, help)
		if f.Required {
			fmt.Fprintf(&b, "\t_ = cmd.MarkFlagRequired(%q)\n", f.Name)
		}
	}
	for _, f := range c.BodyFlags {
		setter, zero := "StringVar", `""`
		switch f.Kind {
		case KindBool:
			setter, zero = "BoolVar", "false"
		case KindInt:
			setter, zero = "IntVar", "0"
		}
		fmt.Fprintf(&b, "\tcmd.Flags().%s(&%s, %q, %s, %q)\n", setter, f.GoIdent, f.Name, zero, f.Name)
		if f.Required {
			fmt.Fprintf(&b, "\t_ = cmd.MarkFlagRequired(%q)\n", f.Name)
		}
	}
	b.WriteString("\treturn cmd\n}\n")
	return b.String()
}

func goType(k BodyFlagKind) string {
	switch k {
	case KindBool:
		return "bool"
	case KindInt:
		return "int"
	default:
		return "string"
	}
}

// pascalCase capitalizes a GoIdent-style camelCase name into the PascalCase
// oapi-codegen uses for exported JSON request-body struct fields (e.g.
// "name" -> "Name"). This covers every plain-word body property in the
// current spec. oapi-codegen applies its own initialism rules for words
// like "url"/"id" (e.g. a property named "logo_url" becomes struct field
// "LogoURL", not "LogoUrl") - if `go build` (Task 15) reports an unknown
// field for a specific property, check its real name with
// `go doc ./internal/client <OperationID>JSONRequestBody` and special-case
// it in this function.
func pascalCase(camel string) string {
	if camel == "" {
		return camel
	}
	return strings.ToUpper(camel[:1]) + camel[1:]
}

// EmitRegisterFile renders register.gen.go, which wires every command in
// cmds onto its tag/group parent. Task 11's BuildCommandSpecs already
// empties Spec.Tag for what was the OpenAPI "common" tag (its commands
// don't belong under a real resource) — an empty Tag here means "attach
// directly to root, ungrouped," per the design spec.
func EmitRegisterFile(w io.Writer, cmds []GeneratedCommand) error {
	var b strings.Builder
	b.WriteString("// Code generated by internal/generator. DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	b.WriteString(`import "github.com/spf13/cobra"` + "\n\n")
	b.WriteString("func getOrAddCommand(parent *cobra.Command, use string) *cobra.Command {\n")
	b.WriteString("\tfor _, c := range parent.Commands() {\n\t\tif c.Name() == use {\n\t\t\treturn c\n\t\t}\n\t}\n")
	b.WriteString("\tc := &cobra.Command{Use: use}\n\tparent.AddCommand(c)\n\treturn c\n}\n\n")
	b.WriteString("// Register wires every generated command onto root.\n")
	b.WriteString("func Register(root *cobra.Command) {\n")

	declared := map[string]bool{}
	for _, c := range cmds {
		opID := c.Spec.Operation.OperationID
		if c.Spec.Tag == "" {
			fmt.Fprintf(&b, "\troot.AddCommand(New%sCommand())\n", opID)
			continue
		}

		parentVar := "root"
		pathKey := c.Spec.Tag
		tagVar := c.Spec.Tag + "Cmd"
		if !declared[pathKey] {
			fmt.Fprintf(&b, "\t%s := getOrAddCommand(%s, %q)\n", tagVar, parentVar, c.Spec.Tag)
			declared[pathKey] = true
		}
		parentVar = tagVar

		for _, g := range c.Spec.Group {
			pathKey += "/" + g
			groupVar := c.Spec.Tag + pascalCase(g) + "Cmd"
			if !declared[pathKey] {
				fmt.Fprintf(&b, "\t%s := getOrAddCommand(%s, %q)\n", groupVar, parentVar, g)
				declared[pathKey] = true
			}
			parentVar = groupVar
		}

		fmt.Fprintf(&b, "\t%s.AddCommand(New%sCommand())\n", parentVar, opID)
	}

	b.WriteString("}\n")
	_, err := w.Write([]byte(b.String()))
	return err
}
